Repository prgrms-be-devcourse/BE-04-HiMin, pull requests merged in 2023-09, with the labels that each got.

#33 [HIMIN-119] hotfix java upgrade
  build.gradle
  src/main/java/com/prgrms/himin/member/application/MemberService.java
  src/main/java/com/prgrms/himin/member/dto/request/AddressCreateRequest.java
  src/main/java/com/prgrms/himin/member/dto/request/MemberCreateRequest.java
  src/main/java/com/prgrms/himin/member/dto/request/MemberLoginRequest.java
  src/main/java/com/prgrms/himin/member/dto/response/AddressResponse.java
  src/main/java/com/prgrms/himin/member/dto/response/MemberCreateResponse.java
  src/main/java/com/prgrms/himin/member/dto/response/MemberResponse.java
  src/main/java/com/prgrms/himin/menu/application/MenuService.java
  src/main/java/com/prgrms/himin/menu/dto/request/MenuCreateRequest.java
  src/main/java/com/prgrms/himin/menu/dto/request/MenuOptionCreateRequest.java
  src/main/java/com/prgrms/himin/menu/dto/request/MenuOptionGroupCreateRequest.java
  src/main/java/com/prgrms/himin/menu/dto/request/MenuOptionGroupUpdateRequest.java
  src/main/java/com/prgrms/himin/menu/dto/request/MenuOptionUpdateRequest.java
  src/main/java/com/prgrms/himin/menu/dto/request/MenuUpdateRequest.java
  src/main/java/com/prgrms/himin/menu/dto/response/MenuCreateResponse.java
  src/main/java/com/prgrms/himin/menu/dto/response/MenuOptionCreateResponse.java
  src/main/java/com/prgrms/himin/menu/dto/response/MenuOptionGroupCreateResponse.java
  src/main/java/com/prgrms/himin/menu/dto/response/MenuOptionGroupResponse.java
  src/main/java/com/prgrms/himin/menu/dto/response/MenuOptionResponse.java
  src/main/java/com/prgrms/himin/menu/dto/response/MenuResponse.java
  src/main/java/com/prgrms/himin/order/application/OrderService.java
  src/main/java/com/prgrms/himin/order/dto/request/OrderCreateRequest.java
  src/main/java/com/prgrms/himin/order/dto/request/SelectedMenuOptionRequest.java
  src/main/java/com/prgrms/himin/order/dto/request/SelectedMenuRequest.java
  src/main/java/com/prgrms/himin/order/dto/response/OrderResponse.java
  src/main/java/com/prgrms/himin/order/dto/response/SelectedMenuResponse.java
  src/main/java/com/prgrms/himin/shop/api/ShopController.java
  src/main/java/com/prgrms/himin/shop/application/ShopService.java
  src/main/java/com/prgrms/himin/shop/dto/request/ShopCreateRequest.java
  src/main/java/com/prgrms/himin/shop/dto/request/ShopUpdateRequest.java
  src/main/java/com/prgrms/himin/shop/dto/response/ShopResponse.java
Labels: Sprint-2

#34 [HIMIN-120] refactor : http 상태 코드 CRUD 별로 동일하게 수정
  src/main/java/com/prgrms/himin/shop/api/ShopController.java
Labels: Sprint-2

#35 [HIMIN-121] refactor: 가게 RequestDto Enum Validator 적용
  src/main/java/com/prgrms/himin/shop/application/ShopService.java
  src/main/java/com/prgrms/himin/shop/dto/request/ShopCreateRequest.java
  src/main/java/com/prgrms/himin/shop/dto/request/ShopUpdateRequest.java
Labels: Sprint-2

#37 [HIMIN-123] refactor : 트랜잭션 어노테이션 readonly 옵션 통일
  src/main/java/com/prgrms/himin/menu/application/MenuService.java
Labels: Sprint-2

#36 [HIMIN-122] beommo enum refactoring
  src/main/java/com/prgrms/himin/member/domain/Grade.java
  src/main/java/com/prgrms/himin/menu/domain/Menu.java
  src/main/java/com/prgrms/himin/menu/domain/MenuStatus.java
  src/main/java/com/prgrms/himin/order/domain/OrderStatus.java
  src/main/java/com/prgrms/himin/shop/domain/Category.java
  src/main/java/com/prgrms/himin/shop/domain/Shop.java
  src/main/java/com/prgrms/himin/shop/domain/ShopStatus.java
Labels: Sprint-2

#38 [HIMIN-124] beommo refactoring enter
  src/main/java/com/prgrms/himin/member/api/MemberController.java
  src/main/java/com/prgrms/himin/member/application/MemberService.java
  src/main/java/com/prgrms/himin/member/domain/Address.java
  src/main/java/com/prgrms/himin/menu/api/MenuController.java
  src/main/java/com/prgrms/himin/menu/application/MenuService.java
  src/main/java/com/prgrms/himin/menu/domain/Menu.java
  src/main/java/com/prgrms/himin/menu/domain/MenuOption.java
  src/main/java/com/prgrms/himin/menu/domain/MenuOptionGroup.java
  src/main/java/com/prgrms/himin/shop/api/ShopController.java
  src/main/java/com/prgrms/himin/shop/application/ShopService.java
  src/main/java/com/prgrms/himin/shop/domain/Shop.java
Labels: Sprint-2

#40 [HIMIN-128] refactor : 메뉴 검증 로직 리팩터링
  src/main/java/com/prgrms/himin/menu/application/MenuService.java
  src/main/java/com/prgrms/himin/menu/domain/MenuValidator.java
  src/main/java/com/prgrms/himin/menu/dto/request/MenuOptionGroupCreateRequest.java
  src/main/java/com/prgrms/himin/order/application/OrderService.java
Labels: Sprint-2

#39 [HIMIN-125] feat: ErrorCode 추가
  src/main/java/com/prgrms/himin/global/error/exception/ErrorCode.java
Labels: Sprint-2

#41 [HIMIN-129] refactor : 에러 코드 추가에 따른 유효성 검증 예외 수정
  src/main/java/com/prgrms/himin/global/error/exception/ErrorCode.java
  src/main/java/com/prgrms/himin/member/application/MemberService.java
  src/main/java/com/prgrms/himin/member/domain/Address.java
  src/main/java/com/prgrms/himin/member/domain/Member.java
  src/main/java/com/prgrms/himin/menu/application/MenuService.java
  src/main/java/com/prgrms/himin/menu/domain/Menu.java
  src/main/java/com/prgrms/himin/menu/domain/MenuOption.java
  src/main/java/com/prgrms/himin/menu/domain/MenuOptionGroup.java
  src/main/java/com/prgrms/himin/menu/domain/MenuValidator.java
  src/main/java/com/prgrms/himin/shop/application/ShopService.java
  src/main/java/com/prgrms/himin/shop/domain/Shop.java
Labels: Sprint-2

#42 [HIMIN-130] refactor: collect(Collectors.toList()) → toList() 로 변경
  src/main/java/com/prgrms/himin/member/application/MemberService.java
  src/main/java/com/prgrms/himin/shop/application/ShopService.java
Labels: Sprint-2

#43 [HIMIN-129] refactor : 에러코드 추가에 따른 유효성 검증 수정
  src/main/java/com/prgrms/himin/global/error/exception/ErrorCode.java
  src/main/java/com/prgrms/himin/order/application/OrderService.java
  src/main/java/com/prgrms/himin/order/domain/Order.java
  src/main/java/com/prgrms/himin/order/domain/OrderHistory.java
  src/main/java/com/prgrms/himin/order/domain/OrderItem.java
  src/main/java/com/prgrms/himin/order/domain/SelectedOption.java
Labels: Sprint-2

#44 [HIMIN-129] style : 에러코드 오타 수정
  src/main/java/com/prgrms/himin/shop/domain/Shop.java
Labels: Sprint-2

#45 [NO-JIRA] !hotfix : build.gradle 수정
  build.gradle
Labels: Sprint-2

#46 [HIMIN-132] refactor : api 명세 수정으로 인한 경로 수정
  src/main/java/com/prgrms/himin/menu/api/MenuController.java
  src/main/java/com/prgrms/himin/menu/application/MenuService.java
Labels: Spring-3

#47 [HIMIN-131] test: 가게 test fixture 추가 (domain, request)
  src/test/java/com/prgrms/himin/setup/domain/ShopSetUp.java
  src/test/java/com/prgrms/himin/setup/request/ShopCreateRequestBuilder.java
Labels: Sprint-3

#50 [NO-JIRA] !hotfix : BusinessExceptoin 핸들링 추가
  src/main/java/com/prgrms/himin/global/error/GlobalExceptionHandler.java
Labels: Sprint-3

#52 [HIMIN-133] MemberController 로그인 테스트 구현
  src/test/java/com/prgrms/himin/member/api/MemberControllerTest.java
  src/test/java/com/prgrms/himin/setup/domain/MemberSetUp.java
  src/test/java/com/prgrms/himin/setup/request/MemberLoginRequestBuilder.java
Labels: Sprint-3

#51 [HIMIN-131] test: 가게 다건 조회 제외 ShopController 테스트코드 작성
  src/main/java/com/prgrms/himin/shop/application/ShopService.java
  src/main/java/com/prgrms/himin/shop/dto/request/ShopUpdateRequest.java
  src/test/java/com/prgrms/himin/setup/request/ShopUpdateRequestBuilder.java
  src/test/java/com/prgrms/himin/shop/api/ShopControllerTest.java
Labels: Sprint-3

#49 [HIMIN-146] test : 메뉴 컨트롤러 테스트 구현
  src/main/java/com/prgrms/himin/menu/dto/request/MenuUpdateRequest.java
  src/test/java/com/prgrms/himin/menu/api/MenuControllerTest.java
  src/test/java/com/prgrms/himin/setup/domain/MenuSetUp.java
  src/test/java/com/prgrms/himin/setup/request/MenuCreateRequestBuilder.java
  src/test/java/com/prgrms/himin/setup/request/MenuUpdateRequestBuilder.java
Labels: Sprint-3

#53 [HIMIN-133] MemberController member 조회 테스트 구현
  src/test/java/com/prgrms/himin/member/api/MemberControllerTest.java
  src/test/java/com/prgrms/himin/setup/domain/MemberSetUp.java
Labels: Sprint-3

#54 [HIMIN-148] test : 메뉴 옵션 그룹 생성 테스트 구현
  src/test/java/com/prgrms/himin/menu/api/MenuOptionGroupControllerTest.java
  src/test/java/com/prgrms/himin/setup/domain/MenuOptionGroupSetUp.java
  src/test/java/com/prgrms/himin/setup/request/MenuOptionGroupRequestBuilder.java
Labels: Sprint-3

#55 [HIMIN-147] 회원 업데이트 기능 구현
  src/main/java/com/prgrms/himin/global/error/exception/ErrorCode.java
  src/main/java/com/prgrms/himin/member/api/MemberController.java
  src/main/java/com/prgrms/himin/member/application/MemberService.java
  src/main/java/com/prgrms/himin/member/domain/Member.java
  src/main/java/com/prgrms/himin/member/dto/request/MemberCreateRequest.java
  src/main/java/com/prgrms/himin/member/dto/request/MemberUpdateRequest.java
Labels: Sprint-3

#57 [HIMIN-148] test : 메뉴 옵션 그룹 수정 테스트 구현
  src/main/java/com/prgrms/himin/menu/dto/request/MenuOptionGroupUpdateRequest.java
  src/test/java/com/prgrms/himin/menu/api/MenuOptionGroupControllerTest.java
  src/test/java/com/prgrms/himin/setup/domain/MenuOptionGroupSetUp.java
  src/test/java/com/prgrms/himin/setup/request/MenuOptionGroupUpdateRequestBuilder.java
Labels: Sprint-3

#56 [HIMIN-133] 회원 업데이트 테스트 구현
  src/test/java/com/prgrms/himin/member/api/MemberControllerTest.java
  src/test/java/com/prgrms/himin/setup/request/MemberUpdateRequestBuilder.java
Labels: Sprint-3

#58 [HIMIN-133] test : 회원 삭제 테스트 구현
  src/test/java/com/prgrms/himin/member/api/MemberControllerTest.java
Labels: Sprint-3

#59 [HIMIN-148] test : 메뉴 옵션 그룹 삭제 테스트 구현
  src/test/java/com/prgrms/himin/menu/api/MenuOptionGroupControllerTest.java
Labels: Sprint-3

#62 [HIMIN-150] test : 메뉴 옵션 생성 테스트 구현
  src/test/java/com/prgrms/himin/menu/api/MenuControllerTest.java
  src/test/java/com/prgrms/himin/menu/api/MenuOptionControllerTest.java
  src/test/java/com/prgrms/himin/setup/domain/MenuOptionSetUp.java
  src/test/java/com/prgrms/himin/setup/request/MenuOptionCreateRequestBuilder.java
Labels: Sprint-3

#61 [HIMIN-149] fix: 가게 컨트롤러 테스트 전체 조회 버그 수정
  src/test/java/com/prgrms/himin/shop/api/ShopControllerTest.java
Labels: Sprint-3

#63 [HIMIN-150] test : 메뉴 옵션 수정 테스트 기능 구현
  src/test/java/com/prgrms/himin/menu/api/MenuOptionControllerTest.java
  src/test/java/com/prgrms/himin/setup/request/MenuOptionUpdateRequestBuilder.java
Labels: Sprint-3

#65 [HIMIN-151] address update 구현
  src/main/java/com/prgrms/himin/member/api/MemberController.java
  src/main/java/com/prgrms/himin/member/application/MemberService.java
  src/main/java/com/prgrms/himin/member/domain/Address.java
  src/main/java/com/prgrms/himin/member/dto/request/AddressUpdateRequest.java
Labels: Sprint-3

#64 [HIMIN-150] test : 메뉴 옵션 삭제 테스트 기능 추가
  src/test/java/com/prgrms/himin/menu/api/MenuOptionControllerTest.java
  src/test/java/com/prgrms/himin/setup/domain/MenuOptionSetUp.java
Labels: Sprint-3

#66 [HIMIN-152] feat : PhonePolicy 구현
  src/main/java/com/prgrms/himin/global/util/PhonePolicy.java
  src/main/java/com/prgrms/himin/member/domain/Member.java
  src/main/java/com/prgrms/himin/member/dto/request/MemberCreateRequest.java
  src/main/java/com/prgrms/himin/shop/domain/Shop.java
Labels: Sprint-3

#68 [HIMIN-155] refactor : 회원 주소 조회 할 경우 내부적으로 쿼리 2회에서 1회로 해결할 수 있도록 리팩터링
  src/main/java/com/prgrms/himin/member/application/MemberService.java
  src/main/java/com/prgrms/himin/member/domain/AddressRepository.java
Labels: Sprint-3

#67 [HIMIN-153] Order생성 컨트롤러 테스트 구현
  src/test/java/com/prgrms/himin/order/api/OrderControllerTest.java
  src/test/java/com/prgrms/himin/setup/domain/OrderItemSetUp.java
  src/test/java/com/prgrms/himin/setup/request/OrderCreateRequestBuilder.java
  src/test/java/com/prgrms/himin/setup/request/SelectedMenuOptionRequestBuilder.java
  src/test/java/com/prgrms/himin/setup/request/SelectedMenuRequestBuilder.java
Labels: Sprint-3

#71 [HIMIN-156] refactor : menuValidator의 find책임을 서비스로 전가
  src/main/java/com/prgrms/himin/menu/application/MenuService.java
  src/main/java/com/prgrms/himin/menu/domain/Menu.java
  src/main/java/com/prgrms/himin/menu/domain/MenuValidator.java
  src/main/java/com/prgrms/himin/order/application/OrderService.java
  src/test/java/com/prgrms/himin/menu/api/MenuOptionControllerTest.java
Labels: Sprint-3

#72 [HIMIN-154] Order조회 컨트롤러 테스트 구현
  src/test/java/com/prgrms/himin/order/api/OrderControllerTest.java
  src/test/java/com/prgrms/himin/setup/domain/OrderItemSetUp.java
  src/test/java/com/prgrms/himin/setup/domain/OrderSetUp.java
  src/test/java/com/prgrms/himin/setup/domain/SelectedOptionSetUp.java
Labels: Sprint-4

#75 [HIMIN-135] chore : CI용 yml 작성
  .github/workflows/CI.yml
  src/main/resources/.gitkeep
Labels: Sprint-4

#76 [HIMIN-137] refactor: equals() and hashCode() 삭제
  src/main/java/com/prgrms/himin/member/domain/Address.java
  src/main/java/com/prgrms/himin/menu/domain/Menu.java
  src/main/java/com/prgrms/himin/menu/domain/MenuOption.java
  src/main/java/com/prgrms/himin/menu/domain/MenuOptionGroup.java
  src/main/java/com/prgrms/himin/order/domain/OrderItem.java
  src/main/java/com/prgrms/himin/order/domain/SelectedOption.java
Labels: Sprint-4

#73 [HIMIN-138] feat: 가게 다건 조회 커서 기반 페이지네이션 구현 + 정렬 조건 추가
  src/main/java/com/prgrms/himin/global/error/exception/ErrorCode.java
  src/main/java/com/prgrms/himin/shop/api/ShopController.java
  src/main/java/com/prgrms/himin/shop/application/ShopService.java
  src/main/java/com/prgrms/himin/shop/dao/ShopRepositoryImpl.java
  src/main/java/com/prgrms/himin/shop/domain/ShopRepository.java
  src/main/java/com/prgrms/himin/shop/domain/ShopRepositoryCustom.java
  src/main/java/com/prgrms/himin/shop/domain/ShopSort.java
  src/main/java/com/prgrms/himin/shop/dto/response/ShopsReponse.java
  src/test/java/com/prgrms/himin/setup/domain/ShopSetUp.java
  src/test/java/com/prgrms/himin/shop/api/ShopControllerTest.java
Labels: Sprint-4

#78 [HIMIN-136] refactor : 주문금액 계산로직에 가게 배달팁 추가
  src/main/java/com/prgrms/himin/order/application/OrderService.java
  src/main/java/com/prgrms/himin/order/domain/Order.java
  src/test/java/com/prgrms/himin/order/api/OrderControllerTest.java
  src/test/java/com/prgrms/himin/setup/domain/OrderSetUp.java
Labels: Sprint-4

#79 [HIMIN-166] Delivery 생성 구현
  src/main/java/com/prgrms/himin/HiminApplication.java
  src/main/java/com/prgrms/himin/delivery/api/DeliveryController.java
  src/main/java/com/prgrms/himin/delivery/application/DeliveryService.java
  src/main/java/com/prgrms/himin/delivery/domain/Delivery.java
  src/main/java/com/prgrms/himin/delivery/domain/DeliveryHistory.java
  src/main/java/com/prgrms/himin/delivery/domain/DeliveryHistoryRepository.java
  src/main/java/com/prgrms/himin/delivery/domain/DeliveryRepository.java
  src/main/java/com/prgrms/himin/delivery/domain/DeliveryStatus.java
  src/main/java/com/prgrms/himin/delivery/dto/response/DeliveryResponse.java
  src/main/java/com/prgrms/himin/global/common/BaseEntity.java
  src/main/java/com/prgrms/himin/order/api/OrderController.java
  src/main/java/com/prgrms/himin/order/domain/OrderStatus.java
Labels: Sprint-4

#80 [HIMIN-173] 배차 기능 구현
  src/main/java/com/prgrms/himin/delivery/api/DeliveryController.java
  src/main/java/com/prgrms/himin/delivery/api/RiderController.java
  src/main/java/com/prgrms/himin/delivery/application/DeliveryService.java
  src/main/java/com/prgrms/himin/delivery/application/RiderService.java
  src/main/java/com/prgrms/himin/delivery/domain/Delivery.java
  src/main/java/com/prgrms/himin/delivery/domain/DeliveryHistory.java
  src/main/java/com/prgrms/himin/delivery/domain/DeliveryStatus.java
  src/main/java/com/prgrms/himin/delivery/domain/Rider.java
  src/main/java/com/prgrms/himin/delivery/domain/RiderRepository.java
  src/main/java/com/prgrms/himin/delivery/dto/request/RiderCreateRequest.java
  src/main/java/com/prgrms/himin/delivery/dto/response/DeliveryHistoryResponse.java
  src/main/java/com/prgrms/himin/delivery/dto/response/DeliveryResponse.java
  src/main/java/com/prgrms/himin/delivery/dto/response/RiderResponse.java
  src/main/java/com/prgrms/himin/global/error/exception/ErrorCode.java
  src/main/java/com/prgrms/himin/order/domain/OrderStatus.java
Labels: Sprint-4

#81 [HIMIN-174] feat : 배달 시작 구현
  src/main/java/com/prgrms/himin/delivery/api/DeliveryController.java
  src/main/java/com/prgrms/himin/delivery/application/DeliveryService.java
Labels: Sprint-4

#82 [HIMIN-175] feat : 배달 완료 구현
  src/main/java/com/prgrms/himin/delivery/api/DeliveryController.java
  src/main/java/com/prgrms/himin/delivery/application/DeliveryService.java
Labels: Sprint-4

#83 [HIMIN-167] Spring Event를 이용하여 배달 완료 구현
  src/main/java/com/prgrms/himin/delivery/application/DeliveryService.java
  src/main/java/com/prgrms/himin/delivery/domain/DeliveryHistory.java
  src/main/java/com/prgrms/himin/order/application/OrderService.java
  src/main/java/com/prgrms/himin/order/domain/OrderHistory.java
  src/main/java/com/prgrms/himin/order/dto/response/OrderResponse.java
  src/main/java/com/prgrms/himin/order/event/DeliveryFinishedEvent.java
  src/main/java/com/prgrms/himin/order/event/OrderEventHandler.java
Labels: Sprint-4

#84 [HIMIN-161] feat : 가게와 메뉴를 조인하여 메뉴이름을 포함한 가게를 검색할 수 있도록 수정
  src/main/java/com/prgrms/himin/shop/api/ShopController.java
  src/main/java/com/prgrms/himin/shop/application/ShopService.java
  src/main/java/com/prgrms/himin/shop/dao/ShopRepositoryImpl.java
  src/main/java/com/prgrms/himin/shop/domain/ShopRepositoryCustom.java
  src/main/java/com/prgrms/himin/shop/dto/request/ShopSearchCondition.java
  src/test/java/com/prgrms/himin/shop/api/ShopControllerTest.java
Labels: Sprint-4

#88 [HIMIN-176] feat : 커서 방식의 주문 조회 기능 구현
  src/main/java/com/prgrms/himin/order/api/OrderController.java
  src/main/java/com/prgrms/himin/order/application/OrderService.java
  src/main/java/com/prgrms/himin/order/domain/OrderRepository.java
  src/main/java/com/prgrms/himin/order/domain/OrderRepositoryCustom.java
  src/main/java/com/prgrms/himin/order/domain/OrderRepositoryImpl.java
  src/main/java/com/prgrms/himin/order/dto/request/OrderSearchCondition.java
  src/main/java/com/prgrms/himin/order/dto/response/OrderResponses.java
Labels: Sprint-4

#87 [HIMIN-179] 가게-주문간 조리 시작, 조리완료 이벤트처리 구현
  src/main/java/com/prgrms/himin/global/error/exception/ErrorCode.java
  src/main/java/com/prgrms/himin/order/application/OrderService.java
  src/main/java/com/prgrms/himin/order/domain/OrderHistory.java
  src/main/java/com/prgrms/himin/order/event/CookingFinishedEvent.java
  src/main/java/com/prgrms/himin/order/event/OrderEventHandler.java
  src/main/java/com/prgrms/himin/order/event/StartedCookingEvent.java
  src/main/java/com/prgrms/himin/shop/api/ShopController.java
  src/main/java/com/prgrms/himin/shop/application/ShopService.java
Labels: Sprint-4

#89 [NO-JIRA] !hotfix : OrderService 닫는중괄호 추가
  src/main/java/com/prgrms/himin/order/application/OrderService.java
Labels: Sprint-4

#86 [HIMIN-163] JWT 관련 설정, 토큰, 필터 구현
  build.gradle
  src/main/java/com/prgrms/himin/HiminApplication.java
  src/main/java/com/prgrms/himin/global/config/security/JwtConfig.java
  src/main/java/com/prgrms/himin/global/config/security/WebSecurityConfig.java
  src/main/java/com/prgrms/himin/global/config/security/jwt/Jwt.java
  src/main/java/com/prgrms/himin/global/config/security/jwt/JwtAuthentication.java
  src/main/java/com/prgrms/himin/global/config/security/jwt/JwtAuthenticationFilter.java
  src/main/java/com/prgrms/himin/global/config/security/jwt/JwtAuthenticationProvider.java
  src/main/java/com/prgrms/himin/global/config/security/jwt/JwtAuthenticationToken.java
  src/main/java/com/prgrms/himin/member/api/MemberController.java
  src/main/java/com/prgrms/himin/member/application/MemberService.java
  src/main/java/com/prgrms/himin/member/domain/Member.java
  src/main/java/com/prgrms/himin/member/domain/MemberRepository.java
  src/main/java/com/prgrms/himin/member/dto/request/MemberCreateRequest.java
  src/main/java/com/prgrms/himin/member/dto/response/MemberLoginResponse.java
  src/test/java/com/prgrms/himin/member/api/MemberControllerTest.java
  src/test/java/com/prgrms/himin/setup/domain/MemberSetUp.java
Labels: Sprint-4

#90 [HIMIN-176] feat : 주문 검색할 경우 fetch join 기능 추가 및 검색 가능 옵션 추가
  src/main/java/com/prgrms/himin/order/domain/OrderRepositoryImpl.java
  src/main/java/com/prgrms/himin/order/dto/request/OrderSearchCondition.java
Labels: Sprint-4

#91 [HIMIN-188] Dto validation refactor
  src/main/java/com/prgrms/himin/member/domain/Address.java
  src/main/java/com/prgrms/himin/member/domain/Member.java
  src/main/java/com/prgrms/himin/member/dto/request/AddressCreateRequest.java
  src/main/java/com/prgrms/himin/member/dto/request/AddressUpdateRequest.java
  src/main/java/com/prgrms/himin/member/dto/request/MemberCreateRequest.java
  src/main/java/com/prgrms/himin/member/dto/request/MemberLoginRequest.java
  src/main/java/com/prgrms/himin/member/dto/request/MemberUpdateRequest.java
  src/main/java/com/prgrms/himin/menu/domain/Menu.java
  src/main/java/com/prgrms/himin/menu/domain/MenuOption.java
  src/main/java/com/prgrms/himin/menu/domain/MenuOptionGroup.java
  src/main/java/com/prgrms/himin/menu/dto/request/MenuCreateRequest.java
  src/main/java/com/prgrms/himin/menu/dto/request/MenuOptionCreateRequest.java
  src/main/java/com/prgrms/himin/menu/dto/request/MenuOptionGroupCreateRequest.java
  src/main/java/com/prgrms/himin/menu/dto/request/MenuOptionGroupUpdateRequest.java
  src/main/java/com/prgrms/himin/menu/dto/request/MenuOptionUpdateRequest.java
  src/main/java/com/prgrms/himin/menu/dto/request/MenuUpdateRequest.java
  src/main/java/com/prgrms/himin/order/domain/Order.java
  src/main/java/com/prgrms/himin/order/domain/OrderItem.java
  src/main/java/com/prgrms/himin/order/dto/request/OrderCreateRequest.java
  src/main/java/com/prgrms/himin/order/dto/request/SelectedMenuRequest.java
  src/main/java/com/prgrms/himin/shop/domain/Shop.java
  src/main/java/com/prgrms/himin/shop/dto/request/ShopCreateRequest.java
  src/main/java/com/prgrms/himin/shop/dto/request/ShopUpdateRequest.java
Labels: Sprint-4

#93 [NO-ZIRA] fix: login with jwt
  src/main/java/com/prgrms/himin/member/domain/Member.java
  src/main/java/com/prgrms/himin/member/domain/Permission.java
Labels: Spring-5

#92 [HIMIN-191] feat, refactor : 공용으로 사용할 yml 파일 생성 및 H2 사용하여 테스트 하도록 변경
  .gitignore
  build.gradle
  src/main/resources/application-local-create.yml
  src/main/resources/application-local.yml
  src/main/resources/application-prod.yml
  src/main/resources/application-test.yml
  src/main/resources/application.yml
  src/test/java/com/prgrms/himin/order/api/OrderControllerTest.java
  src/test/resources/application.yml
Labels: Spring-5

#94 [HIMIN-194] test : 가게 생성 성공테스트 작성
  src/main/java/com/prgrms/himin/shop/domain/Shop.java
  src/test/java/com/prgrms/himin/shop/application/ShopServiceTest.java
Labels: Sprint-5

#97 [HIMIN-198] test: 메뉴 생성 테스트 추가
  src/main/java/com/prgrms/himin/menu/domain/Menu.java
  src/test/java/com/prgrms/himin/menu/application/MenuServiceTest.java
Labels: Sprint-5

#96 [HIMIN-197] test : 가게 조회 테스트코드 작성
  src/test/java/com/prgrms/himin/shop/application/ShopServiceTest.java
Labels: Sprint-5

#98 [HIMIN-200] test : 가게 업데이트 테스트 작성
  src/test/java/com/prgrms/himin/shop/application/ShopServiceTest.java
Labels: Sprint-5

#99 [HIMIN-202] test: 메뉴 조회 테스트 추가
  src/test/java/com/prgrms/himin/menu/application/MenuServiceTest.java
Labels: Sprint-5

#101 [HIMIN-204] test: 메뉴 상태 변경 테스트 추가
  src/test/java/com/prgrms/himin/menu/application/MenuServiceTest.java
  src/test/java/com/prgrms/himin/setup/request/MenuUpdateRequestBuilder.java
Labels: Sprint-5

#103 [HIMIN-201] test : 가게 삭제 테스트 구현
  src/test/java/com/prgrms/himin/shop/application/ShopServiceTest.java
Labels: Sprint-5

#104 [NO-ZIRA] fix: 메뉴 서비스 버그 수정
  src/test/java/com/prgrms/himin/menu/application/MenuServiceTest.java
Labels: Sprint-5

#105 [HIMIN-207] test : 가게 다건조회 테스트 작성
  src/test/java/com/prgrms/himin/shop/application/ShopServiceTest.java
Labels: Sprint-6

#106 [HIMIN-218] test : 회원 생성 테스트 구현
  src/test/java/com/prgrms/himin/member/application/MemberServiceTest.java
Labels: Sprint-6

#108 CD yml configure
  .github/workflows/CICD.yml
  appspec.yml
  scripts/deploy.sh
Labels: Sprint-6

#107 [HIMIN-195] feat : 주문 서비스에서 주문 생성 기능 추가
  src/test/java/com/prgrms/himin/order/application/OrderServiceTest.java
  src/test/java/com/prgrms/himin/setup/factory/OrderDomainTestDependencyFactory.java
  src/test/java/com/prgrms/himin/setup/factory/SelectedMenuFactory.java
  src/test/java/com/prgrms/himin/setup/request/MenuCreateRequestBuilder.java
  src/test/java/com/prgrms/himin/setup/request/MenuOptionCreateRequestBuilder.java
  src/test/java/com/prgrms/himin/setup/request/MenuOptionGroupRequestBuilder.java
  src/test/java/com/prgrms/himin/setup/request/SelectedMenuOptionRequestBuilder.java
Labels: Sprint-6

#109 [HIMIN-218] refactor : MemberServiceTest SpringBootTest로 변경
  src/test/java/com/prgrms/himin/member/application/MemberServiceTest.java
Labels: Sprint-6

#111 [HIMIN-205] test: 메뉴 옵션 그룹 테스트 추가
  src/test/java/com/prgrms/himin/menu/application/MenuOptionGroupServiceTest.java
Labels: Sprint-6

#112 [HIMIN-221] test: 메뉴 옵션 테스트 추가
  src/test/java/com/prgrms/himin/menu/application/MenuOptionServiceTest.java
Labels: Sprint-6

#113 [HIMIN-219] test : 회원 로그인 테스트 구현
  src/test/java/com/prgrms/himin/member/application/MemberServiceTest.java
Labels: Sprint-6

#114 [HIMIN-222] 회원 테스트 구현
  src/test/java/com/prgrms/himin/member/application/MemberServiceTest.java
Labels: Sprint-6

#115 [HIMIN-209] test: 배달 서비스 테스트 추가
  src/main/java/com/prgrms/himin/delivery/application/DeliveryService.java
  src/main/java/com/prgrms/himin/delivery/dto/response/DeliveryHistoryResponse.java
  src/main/java/com/prgrms/himin/delivery/dto/response/DeliveryResponse.java
  src/test/java/com/prgrms/himin/delivery/application/DeliveryServiceTest.java
  src/test/java/com/prgrms/himin/setup/domain/DeliverySetUp.java
  src/test/java/com/prgrms/himin/setup/domain/RiderSetUp.java
  src/test/java/com/prgrms/himin/setup/request/RiderCreateRequestBuilder.java
Labels: Sprint-6

#116 [HIMIN-216] shop 리팩터링
  src/main/java/com/prgrms/himin/shop/application/ShopService.java
  src/main/java/com/prgrms/himin/shop/domain/ShopRepository.java
  src/main/java/com/prgrms/himin/shop/dto/response/ShopResponse.java
Labels: Sprint-7

#117 [HIMIN-232] refactor: 회원 비밀번호 검증 후 비번 암호화
  src/main/java/com/prgrms/himin/member/application/MemberService.java
  src/main/java/com/prgrms/himin/member/domain/Member.java
  src/main/java/com/prgrms/himin/member/dto/request/MemberCreateRequest.java
  src/test/java/com/prgrms/himin/member/api/MemberControllerTest.java
  src/test/java/com/prgrms/himin/member/application/MemberServiceTest.java
Labels: Sprint-7

#118 [HIMIN-226] feat : N + 1 문제를 해결하기 위해 기본 배치 사이즈 설정
  src/main/resources/application-local-create.yml
  src/main/resources/application-local.yml
  src/main/resources/application-prod.yml
  src/main/resources/application-test.yml
Labels: Sprint-7

#119 [HIMIN-234] refactor : delivery생성시 orderId validation 추가
  src/main/java/com/prgrms/himin/delivery/application/DeliveryService.java
  src/main/java/com/prgrms/himin/order/domain/OrderValidator.java
  src/test/java/com/prgrms/himin/delivery/application/DeliveryServiceTest.java
Labels: Sprint-7

#120 [HIMIN-236] fix : finishDelivery 트랜잭션 분리 -> 결합
  src/main/java/com/prgrms/himin/order/event/OrderEventHandler.java
  src/test/java/com/prgrms/himin/delivery/application/DeliveryServiceTest.java
Labels: Sprint-7

#121 [HIMIN-192] Mock제외한 전 테스트 @Transactional -> @Sql로 수정
  src/test/java/com/prgrms/himin/delivery/application/DeliveryServiceTest.java
  src/test/java/com/prgrms/himin/member/api/MemberControllerTest.java
  src/test/java/com/prgrms/himin/member/application/MemberServiceTest.java
  src/test/java/com/prgrms/himin/menu/api/MenuControllerTest.java
  src/test/java/com/prgrms/himin/menu/api/MenuOptionControllerTest.java
  src/test/java/com/prgrms/himin/menu/api/MenuOptionGroupControllerTest.java
  src/test/java/com/prgrms/himin/menu/application/MenuOptionGroupServiceTest.java
  src/test/java/com/prgrms/himin/menu/application/MenuOptionServiceTest.java
  src/test/java/com/prgrms/himin/order/api/OrderControllerTest.java
  src/test/java/com/prgrms/himin/shop/api/ShopControllerTest.java
  src/test/resources/truncate.sql
Labels: Sprint-7

#122 [HIMIN-195] test : setup을 이용한 fixture를 사용하여 주문 서비스 테스트 하도록 기능 변경
  src/test/java/com/prgrms/himin/order/application/OrderServiceTest.java
Labels: Sprint-7

#123 [HIMIN-225] 개행 수정
  src/main/java/com/prgrms/himin/delivery/api/DeliveryController.java
  src/main/java/com/prgrms/himin/delivery/application/DeliveryService.java
  src/main/java/com/prgrms/himin/delivery/domain/DeliveryHistory.java
  src/main/java/com/prgrms/himin/delivery/dto/request/RiderCreateRequest.java
  src/main/java/com/prgrms/himin/delivery/dto/response/DeliveryHistoryResponse.java
  src/main/java/com/prgrms/himin/delivery/dto/response/RiderResponse.java
  src/main/java/com/prgrms/himin/global/config/security/WebSecurityConfig.java
  src/main/java/com/prgrms/himin/global/config/security/jwt/Jwt.java
  src/main/java/com/prgrms/himin/global/config/security/jwt/JwtAuthenticationFilter.java
  src/main/java/com/prgrms/himin/global/config/security/jwt/JwtAuthenticationProvider.java
  src/main/java/com/prgrms/himin/member/dto/request/AddressCreateRequest.java
  src/main/java/com/prgrms/himin/menu/api/MenuController.java
  src/main/java/com/prgrms/himin/menu/application/MenuService.java
  src/main/java/com/prgrms/himin/menu/dto/request/MenuOptionCreateRequest.java
  src/main/java/com/prgrms/himin/menu/dto/response/MenuOptionGroupCreateResponse.java
  src/main/java/com/prgrms/himin/shop/api/ShopController.java
  src/main/java/com/prgrms/himin/shop/application/ShopService.java
  src/test/java/com/prgrms/himin/delivery/application/DeliveryServiceTest.java
  src/test/java/com/prgrms/himin/menu/api/MenuControllerTest.java
  src/test/java/com/prgrms/himin/menu/api/MenuOptionGroupControllerTest.java
  src/test/java/com/prgrms/himin/menu/application/MenuOptionGroupServiceTest.java
  src/test/java/com/prgrms/himin/menu/application/MenuOptionServiceTest.java
  src/test/java/com/prgrms/himin/menu/application/MenuServiceTest.java
  src/test/java/com/prgrms/himin/setup/domain/MemberSetUp.java
  src/test/java/com/prgrms/himin/setup/domain/MenuOptionSetUp.java
  src/test/java/com/prgrms/himin/setup/domain/MenuSetUp.java
  src/test/java/com/prgrms/himin/setup/domain/OrderItemSetUp.java
  src/test/java/com/prgrms/himin/setup/domain/OrderSetUp.java
  src/test/java/com/prgrms/himin/setup/domain/ShopSetUp.java
  src/test/java/com/prgrms/himin/setup/factory/OrderDomainTestDependencyFactory.java
  src/test/java/com/prgrms/himin/setup/request/MemberLoginRequestBuilder.java
  src/test/java/com/prgrms/himin/setup/request/MenuCreateRequestBuilder.java
  src/test/java/com/prgrms/himin/setup/request/MenuOptionCreateRequestBuilder.java
  src/test/java/com/prgrms/himin/setup/request/MenuOptionGroupUpdateRequestBuilder.java
  src/test/java/com/prgrms/himin/setup/request/MenuOptionUpdateRequestBuilder.java
  src/test/java/com/prgrms/himin/setup/request/MenuUpdateRequestBuilder.java
  src/test/java/com/prgrms/himin/setup/request/RiderCreateRequestBuilder.java
  src/test/java/com/prgrms/himin/shop/api/ShopControllerTest.java
Labels: Sprint-7

#126 [HIMIN-228] docs: readme 파일 수정
  README.md
Labels: Sprint-8

#124 [HIMIN-195] test : 주문 서비스 테스트 추가
  src/test/java/com/prgrms/himin/order/application/OrderServiceTest.java
  src/test/java/com/prgrms/himin/setup/factory/SelectedMenuFactory.java
  src/test/java/com/prgrms/himin/setup/factory/SelectedMenuRequestFactory.java
Labels: Sprint-7

#128 [HIMIN-229] 가게와 주문에 대한 Spring Rest Docs 작성
  src/main/java/com/prgrms/himin/shop/api/ShopController.java
  src/main/java/com/prgrms/himin/shop/application/ShopService.java
  src/main/java/com/prgrms/himin/shop/dto/response/ShopsResponse.java
  src/test/java/com/prgrms/himin/order/docs/OrderDocumentationTest.java
  src/test/java/com/prgrms/himin/setup/response/OrderResponseBuilder.java
  src/test/java/com/prgrms/himin/setup/response/ShopResponseBuilder.java
  src/test/java/com/prgrms/himin/setup/response/ShopsResponseBuilder.java
  src/test/java/com/prgrms/himin/shop/api/ShopControllerTest.java
  src/test/java/com/prgrms/himin/shop/application/ShopServiceTest.java
  src/test/java/com/prgrms/himin/shop/docs/ShopDocumentationTest.java
Labels: Sprint-8

#131 [HIMIN-228] test : 메뉴, 메뉴 옵션 그룹, 메뉴 옵션 API restdocs 추가
  src/test/java/com/prgrms/himin/menu/api/MenuControllerTest.java
  src/test/java/com/prgrms/himin/menu/api/MenuOptionGroupControllerTest.java
  src/test/java/com/prgrms/himin/menu/docs/MenuDocumentationTest.java
  src/test/java/com/prgrms/himin/menu/docs/MenuOptionDocumentationTest.java
  src/test/java/com/prgrms/himin/menu/docs/MenuOptionGroupDocumentationTest.java
  src/test/java/com/prgrms/himin/setup/response/MenuCreateResponseBuilder.java
  src/test/java/com/prgrms/himin/setup/response/MenuOptionCreateResponseBuilder.java
  src/test/java/com/prgrms/himin/setup/response/MenuOptionGroupCreateResponseBuilder.java
  src/test/java/com/prgrms/himin/setup/response/MenuResponseBuilder.java
Labels: Sprint-8

#130 [HIMIN-229] test : 주문 다건조회 restdocs test 작성
  src/main/java/com/prgrms/himin/order/api/OrderController.java
  src/main/java/com/prgrms/himin/order/dto/request/OrderSearchCondition.java
  src/test/java/com/prgrms/himin/member/docs/MemberDocumentationTest.java
  src/test/java/com/prgrms/himin/order/docs/OrderDocumentationTest.java
  src/test/java/com/prgrms/himin/setup/response/OrderResponseBuilder.java
  src/test/java/com/prgrms/himin/setup/response/OrderResponsesBuilder.java
Labels: Sprint-8

#132 [HIMIN-228] test : 주문 단건 조회 restdocs 추가
  src/test/java/com/prgrms/himin/order/docs/OrderDocumentationTest.java
Labels: Sprint-8

#133 [NO-ZIRA] refactor: JWT를 이용한 로그인 로직 이동 & [HIMIN-229] test: 로그인 테스트 추가
  src/main/java/com/prgrms/himin/global/config/security/WebSecurityConfig.java
  src/main/java/com/prgrms/himin/global/config/security/jwt/JwtAuthenticationFilter.java
  src/main/java/com/prgrms/himin/global/config/security/jwt/JwtAuthenticationProvider.java
  src/main/java/com/prgrms/himin/member/api/MemberController.java
  src/main/java/com/prgrms/himin/member/application/MemberService.java
  src/main/java/com/prgrms/himin/member/domain/Member.java
  src/test/java/com/prgrms/himin/member/api/MemberControllerTest.java
  src/test/java/com/prgrms/himin/member/application/MemberServiceTest.java
  src/test/java/com/prgrms/himin/member/docs/MemberDocumentationTest.java
  src/test/java/com/prgrms/himin/setup/response/MemberLoginResponseBuilder.java
Labels: Sprint-8

#134 [HIMIN-229] test : adoc 작성
  src/docs/delivery.adoc
  src/docs/menu.adoc
  src/test/java/com/prgrms/himin/delivery/docs/DeliveryDocumentationTest.java
  src/test/java/com/prgrms/himin/menu/api/MenuControllerTest.java
  src/test/java/com/prgrms/himin/menu/docs/MenuDocumentationTest.java
Labels: Sprint-8

#136 [HIMIN-229] docs: 회원, 주문 도메인 adoc 추가
  src/docs/member.adoc
  src/docs/order.adoc
  src/test/java/com/prgrms/himin/order/docs/OrderDocumentationTest.java
Labels: Sprint-8

#137 [HIMIN-229] 메뉴,가게 adoc 작성
  src/docs/menu.adoc
  src/docs/menuOption.adoc
  src/docs/menuOptionGroup.adoc
  src/docs/shop.adoc
  src/test/java/com/prgrms/himin/shop/docs/ShopDocumentationTest.java
Labels: Sprint-8

#135 [NO-ZIRA] refactor : 주문 다건 조회 역할과 책임을 고려하여 리팩토링
  src/main/java/com/prgrms/himin/order/application/OrderService.java
  src/main/java/com/prgrms/himin/order/domain/OrderRepository.java
  src/main/java/com/prgrms/himin/order/domain/OrderRepositoryImpl.java
  src/test/java/com/prgrms/himin/order/application/OrderServiceTest.java
Labels: Sprint-8

#138 [HIMIN-229] feat : restdocs html 생성
  BOOT-INF/classes/static/docs/delivery.html
  BOOT-INF/classes/static/docs/index.html
  BOOT-INF/classes/static/docs/member.html
  BOOT-INF/classes/static/docs/menu.html
  BOOT-INF/classes/static/docs/menuOption.html
  BOOT-INF/classes/static/docs/menuOptionGroup.html
  BOOT-INF/classes/static/docs/order.html
  BOOT-INF/classes/static/docs/shop.html
  build.gradle
  src/docs/asciidoc/delivery.adoc
  src/docs/asciidoc/index.adoc
  src/docs/asciidoc/member.adoc
  src/docs/asciidoc/menu.adoc
  src/docs/asciidoc/menuOption.adoc
  src/docs/asciidoc/menuOptionGroup.adoc
  src/docs/asciidoc/order.adoc
  src/docs/asciidoc/shop.adoc
  src/main/resources/static/docs/delivery.html
  src/main/resources/static/docs/index.html
  src/main/resources/static/docs/member.html
  src/main/resources/static/docs/menu.html
  src/main/resources/static/docs/menuOption.html
  src/main/resources/static/docs/menuOptionGroup.html
  src/main/resources/static/docs/order.html
  src/main/resources/static/docs/shop.html
Labels: Sprint-8

#141 [HIMIN-229] Update README.md
  README.md
Labels: Sprint-8

#142 [NO-JIRA] docs: readme 파일 수정
  README.md
Labels: Sprint-8
